name: zuora-workflows
recipe: laravel

config:
  php: '8.4'
  composer_version: '2'
  via: nginx
  webroot: public
  database: mariadb:11.4
  cache: redis
  xdebug: true
services:
  node:
    type: node:23
    build:
      - "npm install -g yarn"
events:
  post-start:
    - appserver: composer install
    - node: yarn install
    - node: yarn build
tooling:
  yarn:
    service: node
  npx:
    service: node
